In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

from sklearn.svm import OneClassSVM

In [ ]:
df=pd.read_csv('/content/creditcard.csv')
df.head()
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 111004 entries, 0 to 111003
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    111004 non-null  int64
 1   V1      111004 non-null  float64
 2   V2      111004 non-null  float64
 3   V3      111004 non-null  float64
 4   V4      111004 non-null  float64
 5   V5      111004 non-null  float64
 6   V6      111004 non-null  float64
 7   V7      111004 non-null  float64
 8   V8      111004 non-null  float64
 9   V9      111004 non-null  float64
 10  V10     111004 non-null  float64
 11  V11     111004 non-null  float64
 12  V12     111004 non-null  float64
 13  V13     111004 non-null  float64
 14  V14     111004 non-null  float64
 15  V15     111004 non-null  float64
 16  V16     111004 non-null  float64
 17  V17     111004 non-null  float64
 18  V18     111004 non-null  float64
 19  V19     111004 non-null  float64
 20  V20     111004 non-null  float64
 21  V21     111004 non-null  float64
 22  V22     111004 non-null  float64
 23  V23     111003 non-null  float64
 24  V24     111003 non-null  float64
 25  V25     111003 non-null  float64
 26  V26     111003 non-null  float64
 27  V27     111003 non-null  float64
 28  V28     111003 non-null  float64
 29  Amount  111003 non-null  float64
 30  Class   111003 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 26.3 MB

(111004, 31)

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
df=df.dropna()

In [ ]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [1]:
df = df.drop_duplicates()

NameError: name 'df' is not defined

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df["Class"].value_counts()

Class
0.0    110334
1.0       234
Name: count, dtype: int64

In [ ]:
x = df.drop("Class", axis=1)
y = df["Class"]

In [ ]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=42)

In [ ]:
model = OneClassSVM(
    kernel='rbf',
    gamma='scale',
    nu=0.05
)

model.fit(x_scaled)

OneClassSVM(nu=0.05)

In [ ]:
y_pred = model.predict(x_scaled)

In [ ]:
y_pred = model.predict(x_scaled)
y_anomaly = np.where(y_pred == -1, 1, 0)

In [ ]:
print(":", sum(y_anomaly)/len(y_anomaly))

: 0.05498111258519591

In [ ]:
y_pred = model.predict(x_scaled)
y_anomaly = np.where(y_pred == -1, 1, 0)

df_result = pd.DataFrame(x)
df_result["anomaly"] = y_anomaly

df_result[df_result["anomaly"] == 1].head(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,anomaly
7,7,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,1
18,14,-5.401258,-5.450148,1.186305,1.736239,3.049106,-1.763406,-1.559738,0.160842,1.233090,...,-0.503600,0.984460,2.458589,0.042119,-0.481631,-0.621272,0.392053,0.949594,46.80,1
51,36,-1.004929,-0.985978,-0.038039,3.710061,-6.631951,5.122103,4.371691,-2.006868,-0.278736,...,1.393406,-0.381671,0.969719,0.019445,0.570923,0.333278,0.857373,-0.075538,1402.95,1
69,46,-1.923213,-0.870482,2.320170,1.988776,0.417091,-0.380014,0.472139,-0.557333,-0.649079,...,-0.686488,-0.779268,1.086055,0.518863,-0.363712,3.065576,-0.589022,-0.396110,35.00,1
82,52,-3.005237,2.600138,1.483691,-2.418473,0.306326,-0.824575,2.065426,-1.829347,4.009259,...,-0.852309,-0.181268,-0.163747,0.515821,0.136318,0.460054,-0.251259,-1.105751,1.46,1
83,53,-1.198968,-1.474100,1.840326,-4.515824,0.327567,-0.174469,0.959726,-1.026456,1.700435,...,-0.453169,0.334614,-0.364541,-0.310186,-0.302599,-1.243924,-1.123457,-0.734351,89.17,1
85,55,-4.575093,-4.429184,3.402585,0.903915,3.002224,-0.491078,-2.705393,0.666451,1.922216,...,-0.047365,0.853360,-0.971600,-0.114862,0.408300,-0.304576,0.547785,-0.456297,200.01,1
104,69,-1.766645,2.352984,-0.009955,-0.363736,1.460953,-0.204833,0.905819,-3.384123,0.388546,...,1.964253,-0.883218,-0.247698,-0.758606,0.086450,0.202790,-0.898858,-0.944337,0.76,1
132,83,-1.864990,0.910874,1.724863,-1.748371,0.578943,-0.832531,1.901440,-1.913986,2.112375,...,-0.318597,0.073323,-0.061693,0.547204,-0.466798,0.408030,-2.377933,-1.255549,7.69,1
134,83,-1.897331,0.955626,0.052543,1.276656,-3.323084,3.229911,1.029631,1.515607,-0.059627,...,0.128416,0.776078,0.477537,-0.608981,-1.120892,-0.413851,0.061399,-0.187964,552.18,1

In [ ]:
print(x_train)
print(y_train)

[[ 1.30208466 -1.34238    -0.1581849  ... -1.14769163  0.92381191
  -0.28113132]
 [ 0.46543844  0.79742288  0.20092284 ... -0.02720022  0.07733219
  -0.36499622]
 [-0.10930354 -0.00756386  0.55538607 ... -0.32684405 -0.14060242
  -0.34074381]
 ...
 [ 1.31396177 -0.93454071 -0.96263051 ...  0.07391784 -0.44662961
   1.26083754]
 [-2.45666381 -0.0482959   0.51520335 ...  0.6895626  -0.05353802
  -0.34174312]
 [-0.98528236  0.78642916  0.13929885 ... -0.04809984  0.03053719
  -0.36499622]]
103527    0.0
69716     0.0
47248     0.0
9422      0.0
38371     0.0
         ...
77123     0.0
110703    0.0
104104    0.0
867       0.0
15848     0.0
Name: Class, Length: 88454, dtype: float64

In [ ]:
y_train_pred_raw = model.predict(x_train)
y_train_pred_anomaly = np.where(y_train_pred_raw == -1, 1, 0)

y_test_pred_raw = model.predict(x_test)
y_test_pred_anomaly = np.where(y_test_pred_raw == -1, 1, 0)

print(f"Train Accuracy: {accuracy_score(y_train, y_train_pred_anomaly)}")
print(f"Test Accuracy: {accuracy_score(y_test, y_test_pred_anomaly)}")

Train Accuracy: 0.9519524272503223
Test Accuracy: 0.9504386361580899